apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kfno22y0i-java-quarkus
  janus-idp.io/tekton: kfno22y0i-java-quarkus
  backstage.io/kubernetes-id: kfno22y0i-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kfno22y0i-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
